import { useEffect, useMemo, useRef, useState } from 'react'
import { Download, Printer, Save, Upload } from 'lucide-react'
import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'
import QRCode from 'qrcode'
import { supabase } from './lib/supabase'

type Student={student_id:string;admission_no:string;roll_no?:string;full_name:string;date_of_birth?:string;mobile_primary?:string;academic_year?:string}
const logo='https://res.cloudinary.com/oilisvfi/image/upload/v1786000074/logo_final_frchld.jpg'

export default function IDCardStudio({setToast,onUploadCsv}:{setToast:(message:string)=>void;onUploadCsv:()=>void}){
 const [students,setStudents]=useState<Student[]>([]),[studentId,setStudentId]=useState(''),[className,setClassName]=useState(''),[photoUrl,setPhotoUrl]=useState(''),[photoPreview,setPhotoPreview]=useState(''),[expiry,setExpiry]=useState('2027-03-31'),[qr,setQr]=useState(''),[busy,setBusy]=useState(false)
 const card=useRef<HTMLDivElement>(null),selected=useMemo(()=>students.find(student=>student.student_id===studentId),[students,studentId])
 useEffect(()=>{if(!supabase)return;supabase.from('student_master').select('student_id,admission_no,roll_no,full_name,date_of_birth,mobile_primary,academic_year').eq('is_active',true).order('full_name').then(({data,error})=>error?setToast(error.message):setStudents(data||[]))},[setToast])
 useEffect(()=>{if(!selected){setQr('');return}QRCode.toDataURL(JSON.stringify({school:'SJES',admission:selected.admission_no,id:selected.student_id}),{width:180,margin:1}).then(setQr)},[selected])
 const visiblePhoto=photoPreview||photoUrl
 const makePdf=async()=>{if(!card.current)throw Error('Preview unavailable');const canvas=await html2canvas(card.current,{scale:3,useCORS:true,backgroundColor:'#fff'}),pdf=new jsPDF({orientation:'landscape',unit:'mm',format:[85.6,54]});pdf.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,85.6,54);return pdf.output('blob')}
 const download=async()=>{if(!selected)return setToast('Select a student first');setBusy(true);try{const blob=await makePdf(),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`ID-${selected.admission_no}.pdf`;link.click();setToast('ID card PDF downloaded')}catch(error){setToast(error instanceof Error?error.message:'PDF failed')}setBusy(false)}
 const save=async()=>{if(!selected||!supabase)return setToast('Select a student first');setBusy(true);try{const record={student_id:selected.student_id,student_name:selected.full_name,class_name:className,roll_no:selected.roll_no||null,mobile:selected.mobile_primary||null,photo_url:photoUrl||null,issue_date:new Date().toISOString().slice(0,10),valid_until:expiry,is_active:true};const existing=await supabase.from('student_idcard').select('card_id').eq('student_id',selected.student_id).limit(1).maybeSingle();if(existing.error)throw existing.error;const result=existing.data?.card_id?await supabase.from('student_idcard').update(record).eq('card_id',existing.data.card_id):await supabase.from('student_idcard').insert(record);if(result.error)throw result.error;setToast('Student ID card record saved')}catch(error){setToast(error instanceof Error?error.message:'Save failed')}setBusy(false)}
 return <div className="studio"><section className="studio-panel"><span className="overline">STUDENT_IDCARD</span><h2>Generate student ID card</h2><p>Student details and the finished card record use the supplied Supabase tables.</p><label>Student<select value={studentId} onChange={event=>setStudentId(event.target.value)}><option value="">Select by name or admission number</option>{students.map(student=><option key={student.student_id} value={student.student_id}>{student.full_name} · {student.admission_no}</option>)}</select></label><label>Class name<input value={className} onChange={event=>setClassName(event.target.value)} placeholder="e.g. CLASS VIII"/></label><label>Photo URL<input type="url" value={photoUrl} onChange={event=>setPhotoUrl(event.target.value)} placeholder="https://..."/></label><label>Valid until<input type="date" value={expiry} onChange={event=>setExpiry(event.target.value)}/></label><label className="photo-upload"><Upload/>Preview a local photograph<input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)setPhotoPreview(URL.createObjectURL(file))}}/></label><div className="studio-actions"><button onClick={download} disabled={busy||!selected}><Download/>Download PDF</button><button className="primary" onClick={save} disabled={busy||!selected}><Save/>{busy?'Saving…':'Save card record'}</button><button onClick={()=>window.print()}><Printer/>Print</button><button onClick={onUploadCsv}><Upload/>Upload CSV</button></div></section><section className="preview-stage"><div className="id-card" ref={card}><header><img src={logo}/><div><b>ST. JOHN'S ENGLISH SCHOOL</b><span>Dankuni, Hooghly · 712311</span></div></header><div className="id-body"><div className="student-photo">{visiblePhoto?<img src={visiblePhoto}/>:<span>{selected?selected.full_name.split(' ').slice(0,2).map(part=>part[0]).join(''):'PHOTO'}</span>}</div><div className="id-details"><small>STUDENT IDENTITY CARD</small><h3>{selected?.full_name||'Select a student'}</h3><dl><dt>Admission No.</dt><dd>{selected?.admission_no||'—'}</dd><dt>Class</dt><dd>{className||'—'}</dd><dt>Roll No.</dt><dd>{selected?.roll_no||'—'}</dd><dt>Date of Birth</dt><dd>{selected?.date_of_birth||'—'}</dd><dt>Valid Until</dt><dd>{expiry}</dd></dl></div>{qr&&<img className="id-qr" src={qr}/>}</div><footer><span>9674368297</span><b>PRINCIPAL</b></footer></div><p className="preview-note">Live preview · Standard CR80 card size</p></section></div>
}
