import { FormEvent, useState } from 'react'
import { Eye, EyeOff, GraduationCap, LockKeyhole, User } from 'lucide-react'
import { supabase } from './lib/supabase'
const logo='https://res.cloudinary.com/oilisvfi/image/upload/v1786000074/logo_final_frchld.jpg'
export default function PortalLogin(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const login=username.trim();if(login.includes('@')){const result=await supabase.auth.signInWithPassword({email:login,password});if(result.error)setError(result.error.message)}else{const result=await supabase.functions.invoke('username-login',{body:{username:login,password}});if(result.error||result.data?.error)setError(result.data?.error||'Invalid username or password');else await supabase.auth.setSession({access_token:result.data.access_token,refresh_token:result.data.refresh_token})}setBusy(false)}
 return <main className="auth-page"><div className="auth-orb one"/><div className="auth-orb two"/><section className="auth-shell"><aside><img src={logo} alt="St. John's English School logo"/><span>ST. JOHN'S ENGLISH SCHOOL</span><h1>One school.<br/>One connected system.</h1><p>Secure access for administrators, teachers, office staff, parents and students.</p><div className="auth-features"><b><GraduationCap/>Complete academic workflows</b></div></aside><form onSubmit={submit}><span className="overline">SCHOOL ERP PORTAL</span><h2>Welcome back</h2>{error&&<div className="auth-error">{error}</div>}<label>Username<div><User/><input type="text" required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter your username" autoComplete="username"/></div></label><label>Password<div><LockKeyhole/><input type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label><button className="auth-submit" disabled={busy}>{busy?'Signing in…':'Sign in to ERP'}</button></form></section></main>
}
