-- Complete student admission, academic, parent, contact and medical profile fields.
alter table public.student_master
  add column if not exists admission_date date,
  add column if not exists class_name varchar(50),
  add column if not exists section varchar(50),
  add column if not exists house_name varchar(100),
  add column if not exists student_status varchar(30) default 'Active',
  add column if not exists first_name varchar(80),
  add column if not exists middle_name varchar(80),
  add column if not exists last_name varchar(80),
  add column if not exists blood_group varchar(5),
  add column if not exists nationality varchar(80),
  add column if not exists religion varchar(80),
  add column if not exists category varchar(30),
  add column if not exists mother_tongue varchar(80),
  add column if not exists student_photo_url text,
  add column if not exists student_email varchar(150),
  add column if not exists father_mobile varchar(15),
  add column if not exists father_whatsapp varchar(15),
  add column if not exists father_email varchar(150),
  add column if not exists father_occupation varchar(150),
  add column if not exists mother_mobile varchar(15),
  add column if not exists mother_whatsapp varchar(15),
  add column if not exists mother_email varchar(150),
  add column if not exists mother_occupation varchar(150),
  add column if not exists guardian_name varchar(150),
  add column if not exists guardian_relation varchar(80),
  add column if not exists guardian_mobile varchar(15),
  add column if not exists emergency_contact_name varchar(150),
  add column if not exists emergency_contact_phone varchar(15),
  add column if not exists permanent_address text,
  add column if not exists previous_school varchar(255),
  add column if not exists previous_class varchar(80),
  add column if not exists medical_conditions text,
  add column if not exists allergies text,
  add column if not exists doctor_name varchar(150),
  add column if not exists doctor_phone varchar(15),
  add column if not exists birth_certificate_no varchar(100),
  add column if not exists document_url text;

create index if not exists student_master_class_section_idx on public.student_master(class_name, section, academic_year);
create index if not exists student_master_parent_mobile_idx on public.student_master(father_mobile, mother_mobile);
