-- Extend the existing live ERP schema. Library and transport are not referenced.
create table public.admission_enquiries (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_name text not null, guardian_name text, phone text not null, email text, class_applied text not null, source text, status text default 'new', next_follow_up date, notes text, created_at timestamptz default now());
create table public.admissions (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, enquiry_id uuid references public.admission_enquiries, application_no text not null, student_name text not null, class_applied text not null, application_data jsonb default '{}', status text default 'submitted', submitted_at timestamptz default now(), reviewed_by uuid references public.profiles, unique(school_id,application_no));
create table public.promotions (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students on delete cascade, from_class_id uuid references public.classes, to_class_id uuid references public.classes, academic_session_id uuid references public.academic_sessions, result text, promoted_on date, approved_by uuid references public.profiles);
create table public.homework (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, section_id uuid references public.sections, subject_id uuid references public.subjects, title text not null, description text, assigned_on date default current_date, due_on date, attachment_url text, assigned_by uuid references public.profiles, published boolean default false);
create table public.homework_submissions (id uuid primary key default gen_random_uuid(), homework_id uuid references public.homework on delete cascade, student_id uuid references public.students on delete cascade, answer text, attachment_url text, submitted_at timestamptz, marks numeric(6,2), feedback text, unique(homework_id,student_id));
create table public.lesson_plans (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, subject_id uuid references public.subjects, teacher_id uuid references public.profiles, title text not null, objectives text, content text, starts_on date, ends_on date, status text default 'draft');
create table public.study_materials (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, subject_id uuid references public.subjects, title text not null, description text, provider_file_id text, file_url text, uploaded_by uuid references public.profiles, published_at timestamptz);
create table public.grade_scales (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, name text not null, min_percent numeric(5,2), max_percent numeric(5,2), grade text not null, grade_point numeric(4,2), remarks text);
create table public.report_cards (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, exam_id uuid references public.exams, total_marks numeric(8,2), percentage numeric(5,2), grade text, rank integer, attendance_summary jsonb default '{}', teacher_remark text, principal_remark text, published_at timestamptz, unique(student_id,exam_id));
create table public.expenses (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, voucher_no text not null, category text not null, payee text, description text, amount numeric(12,2) not null, expense_date date not null, payment_method text, attachment_url text, approved_by uuid references public.profiles, created_by uuid references public.profiles, unique(school_id,voucher_no));
create table public.income_entries (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, receipt_no text not null, category text not null, received_from text, description text, amount numeric(12,2) not null, income_date date not null, payment_method text, created_by uuid references public.profiles, unique(school_id,receipt_no));
create table public.fee_concessions (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, fee_head_id uuid references public.fee_heads, kind text not null, value numeric(12,2) not null, reason text, starts_on date, ends_on date, approved_by uuid references public.profiles);
create table public.payroll_components (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, name text not null, component_type text check(component_type in ('earning','deduction')), calculation_type text default 'fixed', value numeric(12,2) default 0, taxable boolean default false);
create table public.staff_salary_components (staff_id uuid references public.staff on delete cascade, component_id uuid references public.payroll_components on delete cascade, amount numeric(12,2) not null, primary key(staff_id,component_id));
create table public.payroll_runs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, staff_id uuid references public.staff, pay_month date not null, gross numeric(12,2) not null, deductions numeric(12,2) default 0, net numeric(12,2) generated always as (gross-deductions) stored, status text default 'draft', paid_at timestamptz, unique(staff_id,pay_month));
create table public.recruitment_applications (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, applicant_name text not null, email text, phone text, position text not null, qualification text, experience_years numeric(4,1), resume_url text, status text default 'applied', interview_at timestamptz, notes text);
create table public.appraisals (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, staff_id uuid references public.staff, review_period text not null, score numeric(5,2), strengths text, improvements text, goals text, reviewed_by uuid references public.profiles, reviewed_at timestamptz);
create table public.certificates (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, certificate_type text not null, certificate_no text not null, issued_on date default current_date, data jsonb default '{}', issued_by uuid references public.profiles, unique(school_id,certificate_no));
create table public.id_cards (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, staff_id uuid references public.staff, card_no text not null, issued_on date, expires_on date, status text default 'active', qr_payload text, unique(school_id,card_no));
create table public.documents (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, staff_id uuid references public.staff, name text not null, category text not null, storage_provider text default 'google_drive', provider_file_id text, mime_type text, size_bytes bigint, uploaded_by uuid references public.profiles, created_at timestamptz default now());
create table public.communication_log (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, channel text not null check(channel in ('email','whatsapp','sms','push')), recipient text not null, subject text, template_key text, status text default 'queued', provider_message_id text, error_message text, sent_by uuid references public.profiles, created_at timestamptz default now(), sent_at timestamptz);
create table public.email_templates (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, key text not null, subject text not null, html_body text not null, variables text[] default '{}', active boolean default true, unique(school_id,key));
create table public.school_events (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, title text not null, description text, starts_at timestamptz not null, ends_at timestamptz, location text, audience text[] default array['all'], created_by uuid references public.profiles);
create table public.school_settings (school_id uuid primary key references public.schools on delete cascade, settings jsonb not null default '{}', updated_by uuid references public.profiles, updated_at timestamptz default now());

create index idx_admission_enquiries_school on public.admission_enquiries(school_id,status);
create index idx_homework_class_due on public.homework(class_id,due_on);
create index idx_report_cards_student on public.report_cards(student_id,exam_id);
create index idx_expenses_school_date on public.expenses(school_id,expense_date);
create index idx_documents_school on public.documents(school_id,category);

do $$ declare t text; begin foreach t in array array['admission_enquiries','admissions','promotions','homework','lesson_plans','study_materials','grade_scales','report_cards','expenses','income_entries','fee_concessions','payroll_components','payroll_runs','recruitment_applications','appraisals','certificates','id_cards','documents','communication_log','email_templates','school_events','school_settings'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "school members read %1$s" on public.%1$I for select to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'',''accountant'',''hr_manager'',''staff'',''parent'',''student'']::public.app_role[]))',t); execute format('create policy "school managers write %1$s" on public.%1$I for all to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'']::public.app_role[])) with check (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'']::public.app_role[]))',t); end loop; end $$;
alter table public.homework_submissions enable row level security;
alter table public.staff_salary_components enable row level security;
create policy "school members read homework submissions" on public.homework_submissions for select to authenticated using(exists(select 1 from public.homework h where h.id=homework_id and public.has_school_role(h.school_id,array['super_admin','school_admin','principal','vice_principal','teacher','parent','student']::public.app_role[])));
create policy "teachers manage homework submissions" on public.homework_submissions for all to authenticated using(exists(select 1 from public.homework h where h.id=homework_id and public.has_school_role(h.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[]))) with check(exists(select 1 from public.homework h where h.id=homework_id and public.has_school_role(h.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[])));
create policy "authorized staff read salaries" on public.staff_salary_components for select to authenticated using(exists(select 1 from public.staff s where s.id=staff_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','accountant','hr_manager']::public.app_role[])));
create policy "authorized staff manage salaries" on public.staff_salary_components for all to authenticated using(exists(select 1 from public.staff s where s.id=staff_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','accountant','hr_manager']::public.app_role[]))) with check(exists(select 1 from public.staff s where s.id=staff_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','accountant','hr_manager']::public.app_role[])));

update public.schools set name='St. John''s English School', address='Dankuni, Hooghly 712311', city='Dankuni', state='West Bengal', pincode='712311', phone='9674368297' where id=(select id from public.schools order by created_at limit 1);
