-- School On-inspired eDiary and engagement workflows. Library and transport remain excluded.
create table public.class_diary (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, teacher_id uuid references public.profiles, entry_date date not null default current_date, title text not null, body text not null, attachments jsonb default '[]', published boolean default false, created_at timestamptz default now());
create table public.syllabus_progress (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, subject_id uuid references public.subjects, teacher_id uuid references public.profiles, unit_title text not null, total_topics integer not null default 0, completed_topics integer not null default 0, status text default 'not_started', updated_at timestamptz default now(), check(completed_topics between 0 and total_topics));
create table public.live_classes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, class_id uuid references public.classes, subject_id uuid references public.subjects, teacher_id uuid references public.profiles, title text not null, meeting_url text not null, starts_at timestamptz not null, ends_at timestamptz, status text default 'scheduled', recording_url text, created_at timestamptz default now());
create table public.online_exams (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, exam_id uuid references public.exams, title text not null, instructions text, duration_minutes integer not null default 60, starts_at timestamptz, ends_at timestamptz, status text default 'draft', created_at timestamptz default now());
create table public.daily_feeds (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, title text not null, body text not null, media_url text, audience text default 'all', published_at timestamptz, created_by uuid references public.profiles, created_at timestamptz default now());
create table public.behaviour_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students on delete cascade, category text not null, points integer default 0, notes text not null, recorded_by uuid references public.profiles, recorded_at timestamptz default now(), visibility text default 'parent');
create table public.health_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid not null references public.students on delete cascade, medical_history text, allergies text, medications text, special_care text, emergency_contact text, updated_at timestamptz default now(), unique(student_id));
create table public.meeting_requests (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, student_id uuid references public.students, teacher_id uuid references public.profiles, title text not null, starts_at timestamptz not null, status text default 'requested', parent_response text, notes text, created_at timestamptz default now());
create table public.consent_requests (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, title text not null, description text not null, event_date date, due_date date, audience text default 'all', status text default 'draft', created_by uuid references public.profiles, created_at timestamptz default now());
create table public.feedback_tickets (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, submitted_by uuid references public.profiles, category text not null, subject text not null, message text not null, status text default 'open', priority text default 'normal', assigned_to uuid references public.profiles, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.media_gallery (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, title text not null, album text not null, media_url text not null, visibility text default 'all', published_at timestamptz, created_by uuid references public.profiles);
create table public.digital_almanac (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, title text not null, category text not null, content text not null, published_at timestamptz, created_by uuid references public.profiles, created_at timestamptz default now());
create table public.udise_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, academic_year text not null, data_section text not null, record_key text not null, record_value text, status text default 'draft', updated_at timestamptz default now(), unique(school_id,academic_year,data_section,record_key));
create table public.account_ledgers (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools on delete cascade, name text not null, group_name text not null, opening_balance numeric(14,2) default 0, balance_type text default 'debit', is_active boolean default true, created_at timestamptz default now(), unique(school_id,name));

create index idx_class_diary_school_date on public.class_diary(school_id,entry_date);
create index idx_feed_school_publish on public.daily_feeds(school_id,published_at);
create index idx_behaviour_student on public.behaviour_records(student_id,recorded_at);
create index idx_feedback_school_status on public.feedback_tickets(school_id,status);

do $$ declare t text; begin
  foreach t in array array['class_diary','syllabus_progress','live_classes','online_exams','daily_feeds','behaviour_records','health_records','meeting_requests','consent_requests','feedback_tickets','media_gallery','digital_almanac','udise_records','account_ledgers'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy "school members read %1$s" on public.%1$I for select to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'',''accountant'',''hr_manager'',''staff'',''parent'',''student'']::public.app_role[]))',t);
    execute format('create policy "school staff manage %1$s" on public.%1$I for all to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'']::public.app_role[])) with check (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'']::public.app_role[]))',t);
  end loop;
end $$;

-- Financial and compliance records are further restricted to their responsible roles.
drop policy "school members read account_ledgers" on public.account_ledgers;
drop policy "school staff manage account_ledgers" on public.account_ledgers;
create policy "finance reads account ledgers" on public.account_ledgers for select to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[]));
create policy "finance manages account ledgers" on public.account_ledgers for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[]));

-- Confidential student and family records are never school-wide readable.
do $$ declare t text; begin
  foreach t in array array['behaviour_records','health_records','meeting_requests','consent_requests','feedback_tickets'] loop
    execute format('drop policy "school members read %1$s" on public.%1$I',t);
    execute format('drop policy "school staff manage %1$s" on public.%1$I',t);
    execute format('create policy "authorized staff read %1$s" on public.%1$I for select to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'']::public.app_role[]))',t);
    execute format('create policy "authorized staff manage %1$s" on public.%1$I for all to authenticated using (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'']::public.app_role[])) with check (public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'']::public.app_role[]))',t);
  end loop;
end $$;
