-- Remaining operational modules. Library and transport intentionally excluded.
create table public.inventory_items(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,item_code text not null,name text not null,category text,unit text,quantity numeric(12,2) default 0,reorder_level numeric(12,2) default 0,created_at timestamptz default now(),unique(school_id,item_code));
create table public.assets(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,asset_no text not null,name text not null,category text,location text,purchase_date date,purchase_cost numeric(12,2),warranty_until date,status text default 'active',created_at timestamptz default now(),unique(school_id,asset_no));
create table public.hostels(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,name text not null,warden_id uuid references public.staff,capacity integer,address text);
create table public.hostel_rooms(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,hostel_id uuid references public.hostels on delete cascade,room_no text not null,capacity integer not null default 1,unique(hostel_id,room_no));
create table public.hostel_allocations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,student_id uuid references public.students on delete cascade,room_id uuid references public.hostel_rooms,bed_no text,starts_on date,status text default 'active',unique(student_id,status));
create table public.visitors(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,visitor_name text not null,phone text,purpose text not null,person_to_meet text,check_in timestamptz default now(),check_out timestamptz,status text default 'inside',created_by uuid references public.profiles);
create table public.gate_passes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,student_id uuid references public.students,authorized_person text not null,reason text,pass_date date not null,status text default 'requested',approved_by uuid references public.profiles,created_at timestamptz default now());
create table public.chat_threads(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,title text not null,thread_type text not null,is_announcement boolean default false,created_by uuid references public.profiles,created_at timestamptz default now());
create table public.chat_members(thread_id uuid references public.chat_threads on delete cascade,user_id uuid references public.profiles on delete cascade,joined_at timestamptz default now(),primary key(thread_id,user_id));
create table public.chat_messages(id uuid primary key default gen_random_uuid(),thread_id uuid not null references public.chat_threads on delete cascade,sender_id uuid not null references public.profiles,body text not null,attachment_document_id uuid references public.documents,created_at timestamptz default now(),deleted_at timestamptz);
create table public.bulk_import_jobs(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools on delete cascade,import_type text not null,file_name text not null,status text default 'uploaded',total_rows integer default 0,success_rows integer default 0,error_rows integer default 0,error_report jsonb default '[]',created_by uuid references public.profiles,created_at timestamptz default now());

do $$ declare t text; begin foreach t in array array['inventory_items','assets','hostels','hostel_rooms','hostel_allocations','visitors','gate_passes','chat_threads','bulk_import_jobs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "members read %1$s" on public.%1$I for select to authenticated using(public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'',''teacher'',''accountant'',''hr_manager'',''staff'']::public.app_role[]))',t); execute format('create policy "managers write %1$s" on public.%1$I for all to authenticated using(public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'']::public.app_role[])) with check(public.has_school_role(school_id,array[''super_admin'',''school_admin'',''principal'',''vice_principal'']::public.app_role[]))',t); end loop; end $$;
alter table public.chat_members enable row level security; alter table public.chat_messages enable row level security;
create policy "members read own chat memberships" on public.chat_members for select to authenticated using(user_id=auth.uid());
create policy "members read joined messages" on public.chat_messages for select to authenticated using(exists(select 1 from public.chat_members m where m.thread_id=chat_messages.thread_id and m.user_id=auth.uid()));
create policy "members send joined messages" on public.chat_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_members m where m.thread_id=chat_messages.thread_id and m.user_id=auth.uid()));
