-- Complete administrator CRUD permissions for the existing core schema.
create policy "admins manage school" on public.schools for update to authenticated using(public.has_school_role(id,array['super_admin','school_admin','principal']::public.app_role[])) with check(public.has_school_role(id,array['super_admin','school_admin','principal']::public.app_role[]));
create policy "admins manage roles" on public.user_roles for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin']::public.app_role[]));
create policy "admins manage sessions" on public.academic_sessions for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal']::public.app_role[]));
create policy "admins manage classes" on public.classes for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal']::public.app_role[]));
create policy "admins manage sections" on public.sections for all to authenticated using(exists(select 1 from public.classes c where c.id=class_id and public.has_school_role(c.school_id,array['super_admin','school_admin','principal']::public.app_role[]))) with check(exists(select 1 from public.classes c where c.id=class_id and public.has_school_role(c.school_id,array['super_admin','school_admin','principal']::public.app_role[])));
create policy "admins manage enrollments" on public.student_enrollments for all to authenticated using(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal']::public.app_role[]))) with check(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal']::public.app_role[])));
create policy "admins manage guardians" on public.guardians for all to authenticated using(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal']::public.app_role[]))) with check(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal']::public.app_role[])));
create policy "academics manage subjects" on public.subjects for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','vice_principal']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal','vice_principal']::public.app_role[]));
create policy "teachers manage attendance" on public.attendance for all to authenticated using(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[]))) with check(exists(select 1 from public.students s where s.id=student_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[])));
create policy "accounts manage fee heads" on public.fee_heads for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[]));
create policy "accounts manage fee structures" on public.fee_structures for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[]));
create policy "accounts manage fee payments" on public.fee_payments for all to authenticated using(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[])) with check(public.has_school_role(school_id,array['super_admin','school_admin','principal','accountant']::public.app_role[]));
create policy "hr manages staff leaves" on public.staff_leaves for all to authenticated using(exists(select 1 from public.staff s where s.id=staff_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','hr_manager']::public.app_role[]))) with check(exists(select 1 from public.staff s where s.id=staff_id and public.has_school_role(s.school_id,array['super_admin','school_admin','principal','hr_manager']::public.app_role[])));
create policy "academics manage exam schedules" on public.exam_schedules for all to authenticated using(exists(select 1 from public.exams e where e.id=exam_id and public.has_school_role(e.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[]))) with check(exists(select 1 from public.exams e where e.id=exam_id and public.has_school_role(e.school_id,array['super_admin','school_admin','principal','vice_principal','teacher']::public.app_role[])));
create policy "members read timetables" on public.timetables for select to authenticated using(exists(select 1 from public.academic_sessions a where a.id=academic_session_id and public.has_school_role(a.school_id,array['super_admin','school_admin','principal','vice_principal','teacher','parent','student']::public.app_role[])));
create policy "academics manage timetables" on public.timetables for all to authenticated using(exists(select 1 from public.academic_sessions a where a.id=academic_session_id and public.has_school_role(a.school_id,array['super_admin','school_admin','principal','vice_principal']::public.app_role[]))) with check(exists(select 1 from public.academic_sessions a where a.id=academic_session_id and public.has_school_role(a.school_id,array['super_admin','school_admin','principal','vice_principal']::public.app_role[])));
